sudo: required
language: cpp

before_install:
  - sudo apt-get install -y libgflags-dev
  - sudo apt-get install -y libgoogle-glog-dev
  # - yum install gflags-devel.x86_64
  # - yum install glog-devel.x86_64

script: sh build.sh